#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : urlgrabber
Version  : 3.10.2
Release  : 19
URL      : http://urlgrabber.baseurl.org/download/urlgrabber-3.10.2.tar.gz
Source0  : http://urlgrabber.baseurl.org/download/urlgrabber-3.10.2.tar.gz
Summary  : A high-level cross-protocol url-grabber
Group    : Development/Tools
License  : LGPL-2.1
Requires: urlgrabber-bin
Requires: urlgrabber-python
Requires: urlgrabber-data
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
urlgrabber -- A high-level cross-protocol url-grabber
INSTALLATION INSTRUCTIONS
If you want to install urlgrabber on your system, simply open the package
and run:

%package bin
Summary: bin components for the urlgrabber package.
Group: Binaries
Requires: urlgrabber-data

%description bin
bin components for the urlgrabber package.


%package data
Summary: data components for the urlgrabber package.
Group: Data

%description data
data components for the urlgrabber package.


%package python
Summary: python components for the urlgrabber package.
Group: Default

%description python
python components for the urlgrabber package.


%prep
%setup -q -n urlgrabber-3.10.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492443779
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/urlgrabber
/usr/libexec/urlgrabber-ext-down

%files data
%defattr(-,root,root,-)
/usr/share/doc/urlgrabber-3.10.2/ChangeLog
/usr/share/doc/urlgrabber-3.10.2/LICENSE
/usr/share/doc/urlgrabber-3.10.2/README
/usr/share/doc/urlgrabber-3.10.2/TODO

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
